### ISSUE TITLE
project feedback

### ISSUE THREAD

**Issue by adamstep** [chakourix/isw-test-case-react#1]
Hi @chakourix , thanks for the project. I'll put my feedback on both backend/frontend here. I was able to get the project running but noticed a few issues:

- when I add a new member and hit "Submit" while fields are empty, server returns a 500.
- There is no validation for proper formatting of email or phone number, this can be specified on the django model fields.
- There is no duplication detection for email address, I was able to create multiple users with same address.

Let me know if you have any questions!

**Comment by chakourix** [comment]
Thank you Mr. Adam for your comments, i will update the project ASAP and
will let you know.

Thank you

**Comment by chakourix** [comment]
Hello Mr. Adam @adamstep ,

Front and Backend projects are updated.
Your list of bugs has been fixed.

Thank you
